### ISSUE TITLE
Getting Exception calling "Send" with "1" argument(s): "Could not load file or assembly  'System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The  system cannot find the file specified." when using Send-EmailMessage

### ISSUE THREAD

**Issue by tomaustin700** [EvotecIT/Mailozaurr#14]
Hi,
I'm trying to use Mailozaurr to send email using Send-EmailMessage but I'm getting the following exception:
```
WARNING: Send-EmailMessage - Error: Exception calling "Send" with "1" argument(s): "Could not load file or assembly 
'System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The 
system cannot find the file specified."
```

I am using the following arguments with Send-EmailMessage
```
Send-EmailMessage -To 'tom.austin@***.com' -From 'notifications@***.com' `
    -Server 'smtp.office365.com' -Credential $MailCredentials -HTML $output -Subject 'Update Report' -SkipCertificateRevocation

```
This is on Windows 10 21H1

Do you know what could cause this or what I can do to sort it?

Thanks

**Comment by PrzemyslawKlys** [comment]
Can you remove SkipCertificateRecovation and try again? Which PowerShell you use?  Which version of mailozaurr?

**Comment by tomaustin700** [comment]
Hi @PrzemyslawKlys, without SkipCertificateRecovation I'm getting 
```
WARNING: Send-EmailMessage - Error: Exception calling "Connect" with "3" argument(s): "An error occurred while 
attempting to establish an SSL or TLS connection.



The server's SSL certificate could not be validated for the following reasons:

• The server certificate has the following errors:

  • The revocation function was unable to check revocation for the certificate.



"
WARNING: Send-EmailMessage - Possible issue: Port? (587 was used), Using SSL? (StartTls was used)

```

Mailozaurr version is 0.0.12
Powershell version is 5.1.19041.1023

Thanks

**Comment by PrzemyslawKlys** [comment]
I'm pretty sure SkipCertificateRevocation - I need to investigate but it won't solve your problem. You most likely have a proxy or some other traffic inspection in a place where it tries to read TLS or simply ports are closed. I've not added any support for proxy because I am not even sure you can use proxy for 587. Which port are you using to send emails? Maybe simply ports are blocked?

**Comment by tomaustin700** [comment]
You're right and there is SSL traffic inspection in place, I'm sending on port 587. I'm able to send fine using other means of sending email such as C#.

**Comment by PrzemyslawKlys** [comment]
so if you telnet smtp.office365.com 587 you get signal ?

**Comment by tomaustin700** [comment]
I can't telnet as it's not installed but get the following using test-netconnection
![image](https://user-images.githubusercontent.com/6324102/123099960-93e67100-d42a-11eb-99c4-2ebc457e920a.png)

**Comment by PrzemyslawKlys** [comment]
```powershell
if (-not $MailCredentials) {
    $MailCredentials = Get-Credential
}
# this is simple replacement (drag & drop to Send-MailMessage)
Send-EmailMessage -To 'przemyslaw.klys@test.pl' -Subject 'Test' -Body 'test me' -SmtpServer 'smtp.office365.com' -From 'przemyslaw.klys@test.pl' `
    -Cc 'przemyslaw.klys@test.pl' -Priority High -Credential $MailCredentials `
    -UseSsl -Port 587 -Verbose
```

Just tried this one, and it worked. What do you get when you try it like that?

**Comment by jstedfast** [comment]
System.Buffers is used by MimeKit/MailKit in order to re-use large byte arrays for I/O purposes.

Likely it needs to get pulled in/loaded by powershell.

I don't think this has anything to do with proxies or SSL.

**Comment by tomaustin700** [comment]
@PrzemyslawKlys Exact same issue I'm afraid

**Comment by PrzemyslawKlys** [comment]
@jstedfast The buffers library is there - I need to check why it isn't getting loaded 

![image](https://user-images.githubusercontent.com/15063294/123115708-95229880-d440-11eb-8b54-0bf532ade7e5.png)

And the libraries are also loaded in the published version

![image](https://user-images.githubusercontent.com/15063294/123116005-d74bda00-d440-11eb-9fc3-00066a19c1b8.png)

It's version 4.6 tho, so that may it. But @tomaustin700  problem with System.Buffers only are visible when one of the options is used, when he disables the version - the error is different 

```
WARNING: Send-EmailMessage - Error: Exception calling "Connect" with "3" argument(s): "An error occurred while 
attempting to establish an SSL or TLS connection.
The server's SSL certificate could not be validated for the following reasons:
• The server certificate has the following errors:
  • The revocation function was unable to check revocation for the certificate.
"
WARNING: Send-EmailMessage - Possible issue: Port? (587 was used), Using SSL? (StartTls was used)
```

Which tells me it's more on connectivity side. The thing is - it works fine on my end for both PS 5.1 and PS 7. Just tested it with O365 just fine. 

@tomaustin700  can you do:

```
Uninstall-Module Mailozaurr -AllVersions
Install-Module -RequiredVersion 0.0.10 -Name Mailozaurr
Import-Module Mailozaurr -Force # you may need to restart Powershell to be able to get rid of all old versions tho
Get-Module Mailozaurr -ListAvailable
```

Make sure only 0.0.10 is there. Retry.

This will give me information whether newest update broke things when I replaced a bunch of DLL's or is it something that is not related to DLL but most likely dependant on your environment.

**Comment by tomaustin700** [comment]
@PrzemyslawKlys I think I'm potentially hitting two issues here, when I'm running 0.0.10 I'm getting the SSL certificate issue (probably due to being behind a proxy) and `SkipCertificateRevocation` isn't available so I'm essentially stuck there with no way to see if the System.Buffers issue manifests. In 0.0.12 I can use `SkipCertificateRevocation` to get past the SSL issue but then hit the System.Buffers problem.

**Comment by PrzemyslawKlys** [comment]
Right, I will try to debug this - but my guess is - it won't solve your issue - because Certificate Revocation basically checks if the script is revoked, and not if the certificate is wrong. It's clear with the use case described here https://github.com/jstedfast/MailKit/issues/520

I believe I need to implement CertificateValidation - http://www.mimekit.net/docs/html/P_MailKit_MailService_ServerCertificateValidationCallback.htm which I will need to tell - ignore everything - even if it's the wrong certificate.

**Comment by PrzemyslawKlys** [comment]
Ok. I've released a new version. Please give it a go

1. As you said you use proxy and that means that any certificate revocation checks would have to go thru proxy. I've opened an issue https://github.com/jstedfast/MailKit/issues/1228 for @jstedfast to see if it's possible to add that or set it so that we don't have to skip revocation checks. The error you're getting without certificate revocation clearly states it's a problem for you. While we can try to ignore it, I think it would be a bit safer to not skip certificate revocation, as, after all, it's a security issue, but instead use proxy for that.
2. I've downgraded Mailkit/MimeKit to 2.12.0 and made sure to use Net Framework vs .NET STandard depending on which PowerShell is used. I'll play with newer versions of Mailkit/MimeKit later on if this will work. 
3. I've added `SkipCertificateValidation` which skips validation altogether. 

Please test it with SkipCertificateRevocation and see if it still brings system buffers error. I believe it shouldn't be throwing any errors because system.buffer is working without any special libraries in PowerShell 5.1 AFAIK. 

![image](https://user-images.githubusercontent.com/15063294/123553551-17ca9100-d77c-11eb-8754-23b303e144a5.png)

If that works and doesn't give you any errors, please also test SkipCertificateValidation to see if at any. I was able to use IpAddress to connect to Office 365 so this may work for you as well. But I still would like to know if the errors are still thrown.

**Comment by jstedfast** [comment]
There's no way to make System.Security's SslStream redirect socket connections through MailKit's proxy (or to specify a proxy to use in any way).

You might be able to set .NET's global proxy that *maybe* SslStream will use?

**Comment by jstedfast** [comment]
This may work: https://docs.microsoft.com/en-us/dotnet/api/system.net.webrequest.defaultwebproxy?view=net-5.0

**Comment by jstedfast** [comment]
Or maybe this: https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultproxy?view=net-5.0

**Comment by PrzemyslawKlys** [comment]
```powershell
$proxy = [System.Net.WebRequest]::GetSystemWebProxy()
$proxy.Credentials = [System.Net.CredentialCache]::DefaultNetworkCredentials
$web = New-Object System.Net.WebClient
$web.proxy = $proxy
$web.UseDefaultCredentials = $true
```

Maybe this could work. Or something from http://woshub.com/using-powershell-behind-a-proxy/ 

Just not sure if you can "globally" force anything in PowerShell use proxy - or you need to be a bit more specific.

**Comment by tomaustin700** [comment]
Hi @PrzemyslawKlys, just tested the new version with `SkipCertificateValidation` and still getting
```
WARNING: Send-EmailMessage - Error: Exception calling "Send" with "1" argument(s): "Could not load file or assembly 
'System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The 
system cannot find the file specified."

Status Error                                                                                                           
------ -----                                                                                                           
 False Exception calling "Send" with "1" argument(s): "Could not load file or assembly 'System.Buffers, Version=4.0....

```

Thanks for assisting with this

**Comment by PrzemyslawKlys** [comment]
If you just type in [System.Buffer] in console does it work for you?

**Comment by tomaustin700** [comment]
Yep that seems fine
![image](https://user-images.githubusercontent.com/6324102/123650929-f7094680-d822-11eb-83ac-cfa519589584.png)

**Comment by PrzemyslawKlys** [comment]
So I've written some short tests. It seems Buffers.ArrayPool is used in source code so I did some testing with it. 

```powershell
Import-Module Mailozaurr -Force

$Type = @(
    [MailKit.Security.SaslMechanismOAuth2]
    [MimeKit.MessagePriority]
    [MimeKit.MimeMessage]
    [MimeKit.InternetAddress]
    [MailKit.Security.SecureSocketOptions]
    [System.Data.DataTable]
    [System.Text.Encoding]
    [Net.ServicePointManager]
    [System.Buffers.BuffersExtensions]
    [Buffers.ArrayPool[int]]
)

$Output = foreach ($T in $Type) {
    try {
        $Item = (Get-Item -LiteralPath ($T).Assembly.Location)
        [PSCustomObject] @{
            Name           = $Item.Name
            FullName       = $Item.FullName
            FileVersion    = $Item.VersionInfo.FileVersion
            ProductVersion = $Item.VersionInfo.ProductVersion
            ProductName    = $Item.VersionInfo.ProductName
        }
    } catch {
        Write-Warning -Message "Couldn't process $T. Exception $($_.Exception.message)"
    }
}
$Output | Format-Table *
```

![image](https://user-images.githubusercontent.com/15063294/123677372-524c3080-d845-11eb-8b2a-0723b18d2ad7.png)

So it would seem System.Buffers works for me in VSCode when I code - because the powershell extension itself is loading it for me. 

When I load it in the PowerShell

![image](https://user-images.githubusercontent.com/15063294/123677452-6a23b480-d845-11eb-9eba-1ec5c8705a94.png)

It's automatically preloaded in PS 7+

![image](https://user-images.githubusercontent.com/15063294/123677533-86275600-d845-11eb-94db-de5891536c46.png)

It's not preloaded in PS 5.1

![image](https://user-images.githubusercontent.com/15063294/123677580-963f3580-d845-11eb-9252-6f1af01a7de6.png)

After adding System.Buffers DLL to the mix

![image](https://user-images.githubusercontent.com/15063294/123677865-e918ed00-d845-11eb-9427-017d8cb8071b.png)

I've released a new version that should solve this issue. Unfortunately for me - things were working correctly because VSCode PowerShell extension made it feel like it's part of the system.

**Comment by tomaustin700** [comment]
Hi @PrzemyslawKlys, everything is working perfectly now. Thanks so much for your assistance and the quick resolution.
