### ISSUE TITLE
SendEmail-OAuthO365 + SASL xoauth2 token refresh

### ISSUE THREAD

**Issue by TheBigBear** [EvotecIT/Mailozaurr#15]
Having done some research into this myself, I think there are two requirements that come together in this.

#1 we need to request the scope ```offline_access``` explicitly for token refreshes to work

#2 the ms o365 smtp oauth2 flow requires an additional SASL XOAUTH2 email header for authentication purposes

Here are the relevant URLs to MS docs on this.

https://docs.microsoft.com/en-gb/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth#get-an-access-token

https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#offline_access

https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess

https://docs.microsoft.com/en-gb/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth#sasl-xoauth2-authentication-for-shared-mailboxes-in-office-365

**Comment by PrzemyslawKlys** [comment]
I've done extensive testing for the offline_access thinking it's a silver bullet to authentication for graph API. Turns out it's not. offline_access only works and is necessary for users when it works in user context and you still want to have the ability to use graph/send emails in automated ways without constant approval flow. 

It doesn't at all is available in application mode. 

For months I've believed that offline_access basically means you can just use one clientid/client secret and request offline_access which will grant me the ability to continue sending graph queries to O365 after the initial 3600 seconds. But it doesn't. It only gives you the ability to be able to automate graph queries / sending email without having to go thru manual approval. That's it.

If you do request a token, it's still valid for 3600 seconds, and you have to refresh it yourself - and you're responsible for that.

I've tested and implemented this in Graphimo - https://github.com/EvotecIT/Graphimo/blob/master/Public/Connect-Graph.ps1 where once a user requests the token, the token is cached and used by anything that further queries the graph, on each query the token lifetime is verified in cache and if it's about to expire, it will automatically as part of normal graph query, refresh that token by doing connect call again without any interaction for the user. I've successfully used an 18h graph query to create 60000 accounts. 

I believe the same approach has to be implemented for Mailozaurr so that token auto-refreshes itself without user interaction.

As for the XOAUTH2 email header - I am not sure what the problem? Can you tell me more? It should already be implemented in MailKit/MimeKit and we just use that.

**Comment by TheBigBear** [comment]
@PrzemyslawKlys ok, sorry guess it was/is a red herring and not a silver bullet. 
I want/need to send smtp authenticated emails. I tried the delegated and app permission models and they both did not see to work. Then I got really optimistic after reading your comments around using MS Graph and oauth2, but that failed too. 
I have to admit that the error might well have been on my side as I was setting up the App registration in Azure AD. 
It kept telling me I was not authenticated even in the delegated user flow, so I assumed it was the missing xoauth2 header line? Do you have a quick summary scribb sheet on how to set up Azure AD App registration including listing any required api permissions and any redirect URLs if they are needed? 
I have also reached out to Glen Scale author of https://github.com/gscales/Powershell-Scripts/blob/master/TLS-SMTP-Oauth-Mod.ps1 on the off chance he can help you out and help make Mailozaurr able to use oauth2 with token refreshes as expected ( whether it be in GRAPH or delegated code flow scenario)

**Comment by PrzemyslawKlys** [comment]
You have it described in the blog post: https://evotec.xyz/mailozaurr-new-mail-toolkit-smtp-imap-pop3-with-support-for-oauth-2-0-and-graphapi-for-powershell/ - section **Playing with SMTP in PowerShell - Microsoft Graph API** with the distinction that I am using Application permissions. 

```powershell
# It seems larger HTML is not supported. Online makes sure it uses less libraries inline
# it may be related to not escaping chars properly for JSON, may require investigation
$Body = EmailBody {
    EmailText -Text 'This is my text'
    EmailTable -DataTable (Get-Process | Select-Object -First 5 -Property Name, Id, PriorityClass, CPU, Product)
} -Online
# Credentials for Graph
$ClientID = '0fb383f1'
$DirectoryID = 'ceb371f6'
$ClientSecret = 'VKDM_'
$Credential = ConvertTo-GraphCredential -ClientID $ClientID -ClientSecret $ClientSecret -DirectoryID $DirectoryID
# Sending email
Send-EmailMessage -From @{ Name = 'Przemysław Kłys'; Email = 'przemyslaw.klys@test1.pl' } -To 'przemyslaw.klys@test.pl' `
    -Credential $Credential -HTML $Body -Subject 'This is another test email 1' -Graph -Verbose -Priority High
```

For delegated permissions most likely the code needs to be adjusted a bit - i need to spend some time and test it out.

**Comment by gscales** [comment]
Application permissions aren't supported in SMTP, IMAP or POP3 in Exchange Online so you need to just focus on using Delegate permissions scenarios. With Token refreshes its more down to a implementation thing, at the moment people could use Connect-oAuth0365 or they could code their own Authentication that would generate the $Credential Object your passing into Send-EmailMessage. It's then up to them to call a Token refresh (eg acquiretokensilent) before they call Send-EmailMessage. To further complicate things if your trying to use this in Automation (eg you don't want any user interaction) having the flexibility outside of Send_EmailMessage is probably an advantage (eg you could use the ROPC grant etc) as it looks like at the moment you want to have an interactive logon and then use Token Refreshes after that ?. One thing that is new in Graph is the ability to create and send a MIME message directly (from May/June) so you build the message with MimeKit you want to send and as long as it less the 4 MB send it via graph using Application permissions as another option.

**Comment by PrzemyslawKlys** [comment]
I've added to `ConvertTo-GraphCredential` - `MsalToken` and `MsalTokenEncrypted` parameters. I've added it so one can use outside authentication using graph API using [MSAL.PS](https://www.powershellgallery.com/packages/MSAL.PS) PowerShell module. Basically `Get-MsalToken` and pass the token you get to ConvertTo-GraphCredential that's supported by Send-EmailMessage. This allows you to use certificates, delegate permissions and other options that's offered by MSAL.PS and I don't have to worry about it anymore :-)

```powershell
# Generating token using Get-MsalToken
$getMsalTokenSplat = @{
    ClientId     = '0fb383f1'
    ClientSecret = 'VKDM_' | ConvertTo-SecureString -AsPlainText
    Authority    = 'https://login.microsoftonline.com/ceb371f6'
}
$MsalToken = Get-MsalToken @getMsalTokenSplat

# Converting it to Credentials object (so that Send-EmailMessage can use it)
$Credential = ConvertTo-GraphCredential -MsalToken $MsalToken.AccessToken

# sending email
Send-EmailMessage -From 'przemyslaw.klys@something.pl' -To 'przemyslaw.klys@something.else' -Credential $Credential -HTML $Body -Subject 'This is another test email 2' -Graph -Verbose -Priority Low -DoNotSaveToSentItems
```
