### ISSUE TITLE
How to get <CR><LF> in body text using plain ASCII input from file

### ISSUE THREAD

**Issue by stethos** [EvotecIT/Mailozaurr#24]
I have a CR/LF terminated text file and do not want to use HTML as a body but stick to plain text:
PS C:\users> Get-Content -path 'd:\foo.txt' -raw
hello
world

Sending out with Send-MailMessage results in 2 lines as needed in my email client but using Send-**E**MailMessage results in 1 line only:
hello world

CMD used:
$StrBody = (Get-Content -Path 'd:\foo.txt' -raw) ; Send-EMailMessage -SmtpServer 'w.x.y.z' -Body $StrBody  -from 'info@foo.com' -To 'foo@foo.com'  -port 25

I'm a Windows user and the result is the same using PS 5.1 and PSCore 7.2.1 (on Mailozaurr 0.0.21)

**Comment by PrzemyslawKlys** [comment]
@jstedfast Do you have any idea what would not be stripped by `[MimeKit.BodyBuilder]::new()` that we're using when it comes to new lines for text?

**Comment by jstedfast** [comment]
I'm thinking that this may be more likely to be an issue with passing the body as a string on the command-line? I'm not sure, though.

Keep in mind that when sending a message, message bodies are ALWAYS formatted with DOS line endings (aka CRLF).

Is the body base64 encoded? That might cause issue if the input has LF instead of CRLF, but otherwise it shouldn't be an issue.

**Comment by stethos** [comment]
![foo](https://user-images.githubusercontent.com/85946767/149408015-bd0635ad-54c0-4b5b-a810-4e7e9fdfc4b2.png)

^^ It's CRLF

**Comment by jstedfast** [comment]
The BodyBuilder class just takes the TextBody and/or HtmlBody string property values and sets them as the Text property on a TextPart when it constructs the message body.

TextBody.Text calls SetText() which just does Encoding.UTF8.GetBytes(). There's no line-ending conversion.

Also note that SmtpClient.Send/Async() makes sure that line endings are CRLF format (mostly needed when running on Linux) since SMTP specifies line endings must be CRLF.

**Comment by stethos** [comment]
![tb](https://user-images.githubusercontent.com/85946767/149625433-7ba799f1-6821-4daf-8e65-8a0ec7c5d328.png)

In order to be sure I saved the email as TXT in Thunderbird. Send-MailMessage (upper) preserves the CRLF (and adds 3 more at the end?) compared to Send-EMaillMessage (lower) which converts it to a space (0x20)

**Comment by jstedfast** [comment]
I can't think of anything in MimeKit/MailKit that would replace CRLF with a space.

Would it be possible to dump your message to a file (before sending via SMTP) so that we can see the raw message being sent before any other software has a chance to modify it?

Ideally it would use the MimeMessage.WriteTo() method.

**Comment by stethos** [comment]
I'm not a programmer and would need guidance on that.

**Comment by PrzemyslawKlys** [comment]
Basically just about here:

https://github.com/EvotecIT/Mailozaurr/blob/5aeaf9d40e27495f07f81844743f796ce954cfac/Public/Send-EmailMessage.ps1#L684

You would need to do:

```powershell
$Message.WriteTo($PathToFile)
```

So you either modify the module a bit, reimport it with Import-Module -Force and try again or I guess we could add some sort of debug method to Mailozaurr.

**Comment by PrzemyslawKlys** [comment]
Here's the code responsible for using BodyBuilder to build HTML/Text and then assign that Body to `$Message.Body`

https://github.com/EvotecIT/Mailozaurr/blob/5aeaf9d40e27495f07f81844743f796ce954cfac/Public/Send-EmailMessage.ps1#L549-L561

**Comment by PrzemyslawKlys** [comment]
So I just did some testing:

![image](https://user-images.githubusercontent.com/15063294/150494842-807d3ddf-9c34-4765-80e4-e901a3478304.png)

![image](https://user-images.githubusercontent.com/15063294/150494904-67595caa-4881-4104-896d-f944172eb51b.png)

So it seems to work. I've not tested it with old version but after upgrading to 3.1.0 which will be used in next release (hopefully).

**Comment by stethos** [comment]
Looks promising - and sorry that I was not yet able to get the dump. During week time I hardly have time for such things and my plan was to deal with it on the upcoming Saturday. But now I wait for the next release.

**Comment by PrzemyslawKlys** [comment]
Added `MimeMessagePath` string which allows saving the message request if we ever need to troubleshoot it

**Comment by PrzemyslawKlys** [comment]
@stethos give new version a try

**Comment by stethos** [comment]
![image](https://user-images.githubusercontent.com/85946767/150595706-f104ed2a-eb2e-4f9d-82d3-15f119a9a302.png)

Sorry, still not working for me in my email client (Outlook and Thunderbird)

**Comment by PrzemyslawKlys** [comment]
what if you use the example, with the file i prepared that's on github?

**Comment by PrzemyslawKlys** [comment]
Ohhh, you're using body.... that's for HTML, you should use Text :-)

**Comment by stethos** [comment]
Gosh, -Text works like a charm! 

Did not think about this one as I just replaced the SendMailMessage by SendEMailMessage withoug digging more deeply into every parameter.

Thank you for all your help and time you have spend on that one.
