### ISSUE TITLE
Adapting "from" with custom name

### ISSUE THREAD

**Issue by sophiegewillig** [EvotecIT/Mailozaurr#39]
Hello all,
I'm using the Mailozaurr with the "ClientID" - "ClientSecret" and "Directory ID"
The script works and my mails are coming in.

However I'm trying to tweak the the From field to have something custom.
I'm using an alias of a shared mailbox to sent and I want to use a specific "Name" that would be shown when the mail arrives.

But it keeps showing the primary mail and linked name of the shared mailbox.

Send-EmailMessage -From @{ Name = 'nametobeshown'; Email = 'alias@maildomain.be' }

**Comment by PrzemyslawKlys** [comment]
I don't think Graph API allows this functionality to exists. Both Exchange and Exchange Online (via SMTP or Graph) use Name that's matched to the real user in AD/Azure AD. You can't really overwrite it as far as I know. 

There are systems which allow this (mostly linux based) and that's why the functionality is there. 

Some docs to read:
- https://learn.microsoft.com/en-us/graph/api/resources/message?view=graph-rest-1.0
- https://learn.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=http
