### ISSUE TITLE
Can't send attachment > 3Mb using Graph

### ISSUE THREAD

**Issue by PowerBugi** [EvotecIT/Mailozaurr#40]
Hello,

When sending mail with attachment bigger than 3mb, (using Graph) i get this error :

```
WARNING: Send-GraphMailMessage - Error during draft message creation: Response status code does not indicate success: 403 (Forbidden). Access is denied. Check credentials and try again.
WARNING: New-GraphAttachment - Error creating upload session: Response status code does not indicate success: 400 (Bad Request).
WARNING: Send-GraphMailMessageDraft - Error: Response status code does not indicate success: 400 (Bad Request). Empty Payload. JSON content expected.
```

And no mail is send.

[I think it's a limitation for Graph](https://learn.microsoft.com/en-us/graph/api/message-post-attachments?view=graph-rest-1.0&tabs=powershell), but do you think we can bypass it using the "Upload Session" method bellow ?

- https://learn.microsoft.com/en-us/graph/outlook-large-attachments?tabs=http

Thank you for the help.

**Comment by PrzemyslawKlys** [comment]
It's already implemented in the newest version... and what you see are errors from you trying to send one using this feature. The problem is Send.Mail is not enough to send email using this one because it first saves a draft message in a mailbox and then uses upload session and then sends the email. That means you need larger permissions on the mailbox itself. You may need Mail.ReadWrite or similar for this feature to work.

**Comment by PowerBugi** [comment]
Oh okay, thank you for the information and sorry for the issue then !

I think it's usefull to know that.
